### ISSUE TITLE
Problems uploading the skill in AWS Lambda - Process exited before 

### ISSUE THREAD

**Issue by amicoleo** [alexa/skill-sample-nodejs-hello-world#5]
I'm just trying to test the hello world skill on AWS lambda, but giving following errors

Execution result
```
{
  "errorMessage": "RequestId: 03d87827-edf4-11e6-8c3c-4db53bca2172 Process exited before completing request"
}
```

Logs
```
START RequestId: 03d87827-edf4-11e6-8c3c-4db53bca2172 Version: $LATEST
2017-02-08T11:44:57.940Z	03d87827-edf4-11e6-8c3c-4db53bca2172	TypeError: Cannot read property 'locale' of undefined
    at AlexaRequestEmitter.HandleLambdaEvent (/var/task/node_modules/alexa-sdk/lib/alexa.js:102:38)
    at AlexaRequestEmitter.Object.defineProperty.value (/var/task/node_modules/alexa-sdk/lib/alexa.js:91:31)
    at exports.handler (/var/task/index.js:7:11)
END RequestId: 03d87827-edf4-11e6-8c3c-4db53bca2172
REPORT RequestId: 03d87827-edf4-11e6-8c3c-4db53bca2172	Duration: 123.38 ms	Billed Duration: 200 ms 	Memory Size: 128 MB	Max Memory Used: 26 MB	
RequestId: 03d87827-edf4-11e6-8c3c-4db53bca2172 Process exited before completing request
```

I follow following instructions for packaging the function: 
http://docs.aws.amazon.com/lambda/latest/dg/nodejs-create-deployment-pkg.html

And my structure is like following: 
**Function.zip** 

**Function/
...index.js
...node_modules/**

What could be the issue? 

------
**EDIT**

I've also tried to set AmazonDynamoDBFullAccess role as specified in 
https://github.com/alexa/skill-sample-nodejs-highlowgame/issues/1
with no success

**Comment by pintocarlos** [comment]
I am also running in this issue. Have you been able to find a solution? @amicoleo 
Thanks.

**Comment by amicoleo** [comment]
No, I didn't. I've eventually used their previous SDK at https://github.com/amzn/alexa-skills-kit-js - which in the meanwhile has been officially deprecated :)

**Comment by pintocarlos** [comment]
I was able to solve this problem. 
For my case, I was making use of language translations in my Alexa skill implementation. The Alexa SDK will look for this locale defined in the event request when using language translations.

You must configure a custom test event that includes the locale param.
You can find this at the top of the menu of the AWS Lamba by going to: ACTIONS -> Configure Test Event.

The request should look something like below, notice the locale defined:

```
{
  "session": {
    "sessionId": "SessionId....",
    "application": {
      "applicationId": "amzn1.ask.skill...."
    },
    "attributes": {},
    "user": {
      "userId": "amzn1.ask.account...."
    },
    "new": true
  },
  "request": {
    "type": "IntentRequest",
    "requestId": "EdwRequestId.9a4a0273-1572-459d-a509-239d2be7ccaf",
    "locale": "en-US",
    "timestamp": "2017-02-21T05:28:26Z",
    "intent": {
      "name": "YourIntentName",
      "slots": {
       }
      }
    }
  },
  "version": "1.0"
}
```

I hope that helps @amicoleo

**Comment by amicoleo** [comment]
Thanks for sharing. I'll try that when I can.

**Comment by jforge** [comment]
I think, this issue could be closed, because the problem was solved by providing information about a correct test event structure.

After running into the same problem I reduced the requirements for a successful test to the following json (replace "TestIntent" with your intent name):

`{
    "session": {
        "application": {
       }
    },
    "request": {
        "type": "IntentRequest",
        "locale": "en-US",
        "intent": {
            "name": "TestIntent"
        }
    }
}
`

A valid test event for the fact skill sample requires at least an empty user node:

`
{
  "session": {
    "application": {},
    "user": {}
  },
  "request": {
    "type": "IntentRequest",
    "locale": "de-DE",
    "intent": {
      "name": "GetNewFactIntent"
    }
  }
}`

**Comment by dman777** [comment]
I am having this issue with `"locale": "en-US"` in my request. I checked my linux server and that locale is selected and available. Any ideas?

**Comment by saumilsdk** [comment]
I too have the same issue. looks like its because request is sending the data as part of "header" and "body" and all data is contained within body. Temporary solution to make it work in local environment is to change "var alexa = Alexa.handler(event, context);" to "var alexa = Alexa.handler(JSON.stringify(event.body), context);" and seems working locally.

**Comment by user1m** [comment]
I Solved this by giving my lambda function more memory. From `128MB - 512MB` using slider under `"Basic Settings"`. Worked like a charm after that.

**Comment by franklin-lobb** [comment]
As @pintocarlos mentioned, the locale attribute is part of the incoming request from Alexa.  If it's not being found, one thing to check would be that the attribute is present in the test request (as suggested by @jforge).  The specific error message of "Process exited before completing request" is simply because the Lambda function stopped executing after the error was encountered and didn't return a response.  Also, since this sample has been updated recently, you might consider starting over if you're looking to get this hello world up and running - there should be little rework.

This issue appears to related to a previous version of the skill or not to the skill in this repo.  If you need more help, another option is head over to our [forums](https://forums.developer.amazon.com/spaces/165/index.html).
